theme: jekyll-theme-hacker
title: Google Photos File Storage
show_downloads: true
github:
  zip_url: https://github.com/jakebacker/googlephotos-filestorage/releases/latest
  tar_url: https://github.com/jakebacker/googlephotos-filestorage/releases/latest
